"""Stop/Node quality rules — gaps C1, C2, C4, C5, C10.

Each rule is a pure function: (Stop) -> list[EntityIssue]. No DB writes.
"""
from __future__ import annotations

from typing import Callable, List

from ..config import (
    DUPLICATE_DISTANCE_M,
    DUPLICATE_NAME_SIMILARITY,
    ECUADOR_BBOX,
    NULL_ISLAND_THRESHOLD,
    PLACEHOLDER_PATTERNS,
    haversine_m,
)
from ..models import EntityIssue, Severity, Stop


def rule_stop_name_placeholder(stop: Stop) -> List[EntityIssue]:
    """C1: Detect 'parada sin nombre', empty, null, 'Bus Stop N', 'Stop {uuid}' patterns.

    phase_origin: 1 (Phase 1 extraction)
    rule_name: stop_name_placeholder
    """
    name = stop.name
    if name is None:
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_name_placeholder", severity=Severity.ERROR,
            description="Stop name is NULL",
            original_value=None, phase_origin=1,
        )]
    for pat in PLACEHOLDER_PATTERNS:
        if pat.search(name):
            return [EntityIssue(
                entity_type="stop", entity_id=stop.stop_id,
                rule_name="stop_name_placeholder", severity=Severity.ERROR,
                description=f"Stop name matches placeholder pattern: {pat.pattern!r}",
                original_value=name, phase_origin=1,
            )]
    return []


def rule_stop_name_empty(stop: Stop) -> List[EntityIssue]:
    """C2: Detect empty or whitespace-only stop names.

    phase_origin: 1
    rule_name: stop_name_empty
    """
    if stop.name is not None and stop.name.strip() == "":
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_name_empty", severity=Severity.ERROR,
            description="Stop name is empty or whitespace-only",
            original_value=stop.name, phase_origin=1,
        )]
    return []


def rule_stop_coords_null_island(stop: Stop) -> List[EntityIssue]:
    """C4a: Coordinates at or near (0, 0) — the "null island" fallback.

    phase_origin: 1
    rule_name: stop_coords_null_island
    """
    if abs(stop.lat) < NULL_ISLAND_THRESHOLD and abs(stop.lon) < NULL_ISLAND_THRESHOLD:
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_coords_null_island", severity=Severity.ERROR,
            description=f"Stop at null island: ({stop.lat}, {stop.lon})",
            original_value=(stop.lat, stop.lon), phase_origin=1,
        )]
    return []


def rule_stop_coords_outside_bbox(stop: Stop) -> List[EntityIssue]:
    """C4b: Coordinates outside the Ecuador continental bbox (non-null-island).

    phase_origin: 1
    rule_name: stop_coords_outside_bbox
    """
    if abs(stop.lat) < NULL_ISLAND_THRESHOLD and abs(stop.lon) < NULL_ISLAND_THRESHOLD:
        return []
    min_lat, min_lon, max_lat, max_lon = ECUADOR_BBOX
    if not (min_lat <= stop.lat <= max_lat and min_lon <= stop.lon <= max_lon):
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_coords_outside_bbox", severity=Severity.ERROR,
            description=f"Stop outside Ecuador bbox: ({stop.lat}, {stop.lon})",
            original_value=(stop.lat, stop.lon), phase_origin=1,
        )]
    return []


def rule_stop_ref_garbage(stop: Stop) -> List[EntityIssue]:
    """C3 (node ref variant): Detect ref fields that are meaningless numbers.

    Only flags STOP-type nodes whose ref looks like a random number (>6 digits).

    phase_origin: 1
    rule_name: stop_ref_garbage
    """
    if stop.node_type != "STOP" or not stop.ref:
        return []
    ref = stop.ref.strip()
    if ref.isdigit() and len(ref) > 6:
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_ref_garbage", severity=Severity.WARNING,
            description=f"Stop ref looks like a random number: {ref!r}",
            original_value=ref, phase_origin=1,
        )]
    return []


def rule_stop_name_uuid_prefix(stop: Stop) -> List[EntityIssue]:
    """C10: Stop name is a UUID prefix fallback like 'Stop a3f7bc12'.

    phase_origin: 5 (generated by build_routes.py fallback)
    rule_name: stop_name_uuid_prefix
    """
    import re
    if stop.name and re.match(r'^Stop [a-f0-9]{8}$', stop.name, re.IGNORECASE):
        return [EntityIssue(
            entity_type="stop", entity_id=stop.stop_id,
            rule_name="stop_name_uuid_prefix", severity=Severity.ERROR,
            description=f"Stop name is UUID prefix fallback: {stop.name!r}",
            original_value=stop.name, phase_origin=5,
        )]
    return []


# ---------------------------------------------------------------------------
# Duplicate detection (operates on a list, not a single stop)
# ---------------------------------------------------------------------------

def _name_similarity(a: str, b: str) -> float:
    """Simple ratio-based name similarity."""
    a_norm = a.strip().lower()
    b_norm = b.strip().lower()
    if a_norm == b_norm:
        return 1.0
    # Character-level similarity (Sørensen–Dice on bigrams)
    if len(a_norm) < 2 or len(b_norm) < 2:
        return 0.0
    bigrams_a = {a_norm[i:i+2] for i in range(len(a_norm) - 1)}
    bigrams_b = {b_norm[i:i+2] for i in range(len(b_norm) - 1)}
    overlap = len(bigrams_a & bigrams_b)
    return (2.0 * overlap) / (len(bigrams_a) + len(bigrams_b))


def rule_duplicate_stops(stops: List[Stop]) -> List[EntityIssue]:
    """C5: Duplicate stops within <15m with similar names.

    This is a batch rule — call once with the full stop list.

    phase_origin: 1
    rule_name: stop_duplicate_nearby
    """
    issues: List[EntityIssue] = []
    seen_pairs: set = set()
    n = len(stops)

    for i in range(n):
        for j in range(i + 1, n):
            a, b = stops[i], stops[j]
            pair_key = tuple(sorted([a.stop_id, b.stop_id]))
            if pair_key in seen_pairs:
                continue

            dist = haversine_m(a.lat, a.lon, b.lat, b.lon)
            if dist > DUPLICATE_DISTANCE_M:
                continue

            name_a = a.name or ""
            name_b = b.name or ""
            sim = _name_similarity(name_a, name_b)
            if sim < DUPLICATE_NAME_SIMILARITY:
                continue

            seen_pairs.add(pair_key)
            issues.append(EntityIssue(
                entity_type="stop", entity_id=a.stop_id,
                rule_name="stop_duplicate_nearby", severity=Severity.ERROR,
                description=(
                    f"Duplicate: {a.stop_id[:8]} & {b.stop_id[:8]} "
                    f"are {dist:.1f}m apart, name similarity {sim:.2f}"
                ),
                original_value={"other_id": b.stop_id, "distance_m": dist, "similarity": sim},
                phase_origin=1,
            ))
    return issues


# ---------------------------------------------------------------------------
# Public RULES list (single-entity rules only; duplicates is batch)
# ---------------------------------------------------------------------------

RULES: List[Callable[[Stop], List[EntityIssue]]] = [
    rule_stop_name_placeholder,
    rule_stop_name_empty,
    rule_stop_coords_null_island,
    rule_stop_coords_outside_bbox,
    rule_stop_ref_garbage,
    rule_stop_name_uuid_prefix,
]

BATCH_RULES = [
    rule_duplicate_stops,
]
